In [2]:
import os
import pandas as pd

pd.set_option("display.max_rows", 50)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)

In [3]:
datasets = {}
for file in os.listdir('.'):
    if file.endswith('.log'):
        name = file.split('.')[0]
        datasets[name] = pd.read_json(file, lines=True)
        datasets[name]["dt_utc"] = pd.to_datetime(datasets[name]["ts"], unit="s", utc=True)


In [4]:
conn = datasets['conn']
conn[:10]

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,ip_proto,ja4l,ja4ls,ja4t,ja4ts,dt_utc
0,1.600466e+09,CWu1AX2Qwtf21YFqO5,fe80::2dcf:e660:be73:d220,54064,ff02::1:3,5355,udp,dns,0.417919,60.0,0.0,S0,True,False,0,D,2,156,0,0,17,,,,,2020-09-18 21:58:09.552098989+00:00
1,1.600466e+09,CNuoKX1qnIuAAh8sSl,fe80::2dcf:e660:be73:d220,64915,ff02::1:3,5355,udp,dns,0.418672,60.0,0.0,S0,True,False,0,D,2,156,0,0,17,,,,,2020-09-18 21:58:10.473416090+00:00
2,1.600466e+09,CzlCV41RZI6whF90Tl,10.42.85.10,64915,224.0.0.252,5355,udp,dns,0.418670,60.0,0.0,S0,True,True,0,D,2,116,0,0,17,,,,,2020-09-18 21:58:10.473429918+00:00
3,1.600466e+09,CGse7L1JnPRt0n8CT3,10.42.85.10,137,10.42.85.255,137,udp,dns,13.992419,1360.0,0.0,S0,True,True,0,D,20,1920,0,0,17,,,,,2020-09-18 21:58:10.548726082+00:00
4,1.600466e+09,ComfMha1n0e3LWIy,10.42.85.10,137,10.42.85.255,137,udp,dns,1.559274,600.0,0.0,S0,True,True,0,D,12,936,0,0,17,,,,,2020-09-18 21:58:38.032150984+00:00
5,1.600466e+09,C8jUv53vRuSwa7bIrc,fe80::2dcf:e660:be73:d220,51121,ff02::1:3,5355,udp,dns,0.418322,48.0,0.0,S0,True,False,0,D,2,144,0,0,17,,,,,2020-09-18 21:58:38.032597065+00:00
6,1.600466e+09,CC9xzPUcX1a7W2exb,10.42.85.10,51121,224.0.0.252,5355,udp,dns,0.418258,48.0,0.0,S0,True,True,0,D,2,104,0,0,17,,,,,2020-09-18 21:58:38.032712935+00:00
7,1.600466e+09,C5aWE84nOrZYQpcVT2,fe80::2dcf:e660:be73:d220,63259,ff02::1:3,5355,udp,dns,0.418192,48.0,0.0,S0,True,False,0,D,2,144,0,0,17,,,,,2020-09-18 21:58:38.032938004+00:00
8,1.600466e+09,CaIcUmyDPpbNxiw0d,10.42.85.10,63259,224.0.0.252,5355,udp,dns,0.418348,48.0,0.0,S0,True,True,0,D,2,104,0,0,17,,,,,2020-09-18 21:58:38.033014059+00:00
9,1.600466e+09,C2oAwFLwOT8jLSLG3,fe80::2dcf:e660:be73:d220,58141,ff02::1:3,5355,udp,dns,0.417778,44.0,0.0,S0,True,False,0,D,2,140,0,0,17,,,,,2020-09-18 21:58:38.033346890+00:00


In [5]:
datasets['dns']['query'].unique()

array(['citadel-dc01', 'C137', 'CITADEL-DC01', 'WPAD', 'ISATAP', 'isatap',
       'wpad', 'dns.msftncsi.com', 'win8.ipv6.microsoft.com',
       'desktop-sdn1rpt.local',
       '_ldap._tcp.default-first-site-name._sites.dc._msdcs.c137.local',
       'wpad.c137.local', 'citadel-dc01.c137.local',
       'xioorhri.c137.local',
       '_ldap._tcp.default-first-site-name._sites.c137.local',
       'settings-win.data.microsoft.com', 'desktop-sdn1rpt.c137.local',
       '115.85.42.10.in-addr.arpa', 'watson.telemetry.microsoft.com',
       'desktop-sdn1rpt', 'DESKTOP-SDN1RPT',
       'v20.events.data.microsoft.com', 'www.bing.com',
       'go.microsoft.com', 'ocsp.digicert.com', 'www.msn.com',
       'nav.smartscreen.microsoft.com', 'smartscreen-prod.microsoft.com',
       'c.msn.com', 'c.bing.com', 'sb.scorecardresearch.com',
       'otf.msn.com', 'api.msn.com', 'img-s-msn-com.akamaized.net',
       'assets.msn.com', 'microsoftedgewelcome.microsoft.com',
       'srtb.msn.com', 'ocsp.msocsp.com

# 1. Exploration du dataset

On commmence par faire quelques statistiques sur les connexions réseau :

In [4]:
conn["id.orig_h"].value_counts().head(100)

id.orig_h
194.61.24.102                29313
10.42.85.115                  2539
10.42.85.10                    737
fe80::2dcf:e660:be73:d220      116
fe80::a926:8915:319b:2238       18
::                               3
Name: count, dtype: int64

In [5]:
conn["id.resp_h"].value_counts().head(20)

id.resp_h
10.42.85.10       30259
192.168.45.1        584
10.90.90.90         355
ff02::1:3            75
224.0.0.252          73
208.80.153.240       72
10.42.85.255         63
72.21.91.29          49
204.79.197.203       47
ff02::1:2            47
208.80.153.224       45
204.79.197.200       43
40.91.125.0          40
70.37.74.6           38
13.107.21.200        30
74.120.184.194       28
52.242.211.89        22
151.101.1.140        20
151.139.128.14       19
74.120.184.204       16
Name: count, dtype: int64

In [6]:
conn["total_bytes"] = conn.get("orig_bytes", 0) + conn.get("resp_bytes", 0)
top_flows_bytes = (
    conn[["id.orig_h", "id.resp_h", "id.resp_p", "proto", "service", "total_bytes", "orig_bytes", "resp_bytes", "duration"]]
    .sort_values("total_bytes", ascending=False)
    .head(20)
)
top_flows_bytes

,id.orig_h,id.resp_h,id.resp_p,proto,service,total_bytes,orig_bytes,resp_bytes,duration
31709,10.42.85.115,104.119.185.124,443,tcp,ssl,37991129.0,1858.0,37989271.0,109.659907
32078,194.61.24.102,10.42.85.10,3389,tcp,ssl,12853439.0,2366216.0,10487223.0,1810.715048
32089,10.42.85.10,10.42.85.115,3389,udp,rdpeudp,6448171.0,73592.0,6374579.0,950.971623
1698,10.42.85.115,104.18.12.165,443,tcp,ssl,4664235.0,2328.0,4661907.0,126.184417
1340,10.42.85.115,23.47.193.50,443,tcp,ssl,4596703.0,4575.0,4592128.0,33.567848
1333,10.42.85.115,143.204.131.79,443,tcp,ssl,4289666.0,993.0,4288673.0,29.046927
1250,10.42.85.115,151.101.1.67,443,tcp,ssl,4101555.0,10810.0,4090745.0,54.299074
31935,10.42.85.115,23.47.52.14,443,tcp,ssl,3130065.0,2387.0,3127678.0,41.379130
155,10.42.85.115,23.47.48.60,443,tcp,ssl,3050041.0,2387.0,3047654.0,2.925606
32335,10.42.85.115,23.47.52.90,443,tcp,ssl,2645142.0,1030.0,2644112.0,1.100630


# 2. Exploration des IPs internes

On va maintenant explorer les IP internes à notre système pour obtenir plus d'informations sur celui-ci.

Les stats semblent nous montrer qu'on a deux IP internes : 
- 10.42.85.115
- 10.42.85.10 
On va tracer les flux entre ces deux IP pour tenter d'identifier laquelle est quoi.

In [7]:
internal_ips = [
    '10.42.85.115',
    '10.42.85.10'
]
filtered = conn[
    conn["id.orig_h"].isin(internal_ips) &
    conn["id.resp_h"].isin(internal_ips)
]
filtered

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,ip_proto,ja4l,ja4ls,ja4t,ja4ts,dt_utc,total_bytes
34,1.600466e+09,Ctuhhq4BPkymR2sU1d,10.42.85.115,49672,10.42.85.10,88,tcp,krb_tcp,0.002332,236.0,208.0,RSTR,True,True,0,ShADdFar,4,408,4,380,6,86_128,62_128,64240_2-1-3-1-1-4_1460_8,8192_2-1-3-1-1-4_1460_8,2020-09-18 21:59:39.779881954+00:00,444.0
35,1.600466e+09,CX091q3aVIqZ284Rb1,10.42.85.115,49673,10.42.85.10,88,tcp,krb_tcp,0.001230,316.0,1579.0,RSTR,True,True,0,ShADdFar,5,528,5,1791,6,78_128,48_128,64240_2-1-3-1-1-4_1460_8,8192_2-1-3-1-1-4_1460_8,2020-09-18 21:59:39.796812057+00:00,1895.0
36,1.600466e+09,C7MEnB4gJNS0KWE1ig,10.42.85.115,49677,10.42.85.10,88,tcp,krb_tcp,0.000928,236.0,208.0,RSTR,True,True,0,ShADdFar,4,408,4,380,6,60_128,78_128,64240_2-1-3-1-1-4_1460_8,8192_2-1-3-1-1-4_1460_8,2020-09-18 21:59:39.800359011+00:00,444.0
37,1.600466e+09,CzYg4o1SQhwLW0ftz6,10.42.85.115,49676,10.42.85.10,88,tcp,krb_tcp,0.001796,1641.0,1615.0,RSTR,True,True,0,ShADadFr,6,1893,6,1867,6,70_128,42_128,64240_2-1-3-1-1-4_1460_8,8192_2-1-3-1-1-4_1460_8,2020-09-18 21:59:39.799643993+00:00,3256.0
38,1.600466e+09,CRiXK61CsWwFq4ZPIj,10.42.85.115,49671,10.42.85.10,389,tcp,ldap_tcp,0.040866,2238.0,2824.0,RSTR,True,True,0,ShADdar,7,2530,6,3076,6,39_128,44_128,64240_2-1-3-1-1-4_1460_8,8192_2-1-3-1-1-4_1460_8,2020-09-18 21:59:39.774713039+00:00,5062.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32714,1.600494e+09,CAXhLa3mHDbThWH24b,10.42.85.115,51193,10.42.85.10,135,tcp,dce_rpc,10.714642,328.0,280.0,SF,True,True,0,ShADdFaf,7,620,5,492,6,306_128,116_128,64240_2-1-3-1-1-4_1460_8,8192_2-1-3-1-1-4_1460_8,2020-09-19 05:37:22.525118113+00:00,608.0
32715,1.600494e+09,CD8qE02csUDE0qMW29,10.42.85.115,52721,10.42.85.10,389,udp,ldap_udp,0.000335,258.0,178.0,SF,True,True,0,Dd,1,286,1,206,17,,,,,2020-09-19 05:37:22.398351908+00:00,436.0
32718,1.600494e+09,Ce4WYo3dUT748WymKh,10.42.85.115,59457,10.42.85.10,53,udp,dns,0.001635,47.0,165.0,SF,True,True,0,Dd,1,75,1,193,17,,,,,2020-09-19 05:38:39.006177902+00:00,212.0
32721,1.600494e+09,Cl2DJT3qHPMwYqu8yh,10.42.85.115,123,10.42.85.10,123,udp,NaN,0.000935,120.0,120.0,SF,True,True,0,Dd,1,148,1,148,17,,,,,2020-09-19 05:38:17.408936977+00:00,240.0


Maintenant qu'on a identifié les flux on peut aggréger par ip_src, ip_dest, port_dest

In [8]:
agg = (
  filtered.groupby(["id.orig_h", "id.resp_h", "id.resp_p"])
      .size()
      .reset_index(name="count")
      .sort_values("count", ascending=False)
)
agg

,id.orig_h,id.resp_h,id.resp_p,count
1,10.42.85.115,10.42.85.10,53,656
5,10.42.85.115,10.42.85.10,389,128
2,10.42.85.115,10.42.85.10,88,42
7,10.42.85.115,10.42.85.10,49155,40
4,10.42.85.115,10.42.85.10,135,40
6,10.42.85.115,10.42.85.10,445,23
3,10.42.85.115,10.42.85.10,123,14
8,10.42.85.115,10.42.85.10,49158,3
0,10.42.85.10,10.42.85.115,3389,2


On peut donc remarquer :
- 10.42.85.115 est probablement une workstation
- 10.42.85.10 est probablement un active directory.
On peut dire cela car **10.42.85.115** fait des requêtes à **10.42.85.10** sur le port 88 (kerberos). Qui est un service d'authentification distribué exposé par un AD.

Il est assez étonnant de voir le RDP ( port 3389 ) depuis l'active directory vers le la machine. 
RDP permet d'ouvrir une session graphique à distance sur un ordinateur mais cela n'est pas censé arriver depuis un AD. Pour se renseigner un peu sur le parc, on va regarder de plus près le service kerberos : 

In [9]:
kerberos = datasets['kerberos']
agg = (
  kerberos.groupby(["service", "client"])
      .size()
      .reset_index(name="count")
      .sort_values("count", ascending=False)
)
agg

,service,client,count
20,krbtgt/C137.LOCAL,DESKTOP-SDN1RPT$/C137.LOCAL,6
19,krbtgt/C137.LOCAL,Administrator/C137.LOCAL,3
26,krbtgt/C137.LOCAL,ricksanchez/C137.LOCAL,3
21,krbtgt/C137.LOCAL,desktop-sdn1rpt$/C137.LOCAL,2
13,desktop-sdn1rpt$,DESKTOP-SDN1RPT$/C137.LOCAL,2
1,LDAP/CITADEL-DC01.C137.local,DESKTOP-SDN1RPT$/C137.LOCAL,1
0,DESKTOP-SDN1RPT$,DESKTOP-SDN1RPT$/C137.LOCAL,1
6,ProtectedStorage/CITADEL-DC01.C137.local,Administrator/C137.LOCAL,1
7,cifs/CITADEL-DC01,Administrator/C137.LOCAL,1
9,cifs/CITADEL-DC01.C137.local,Administrator/C137.LOCAL,1


Comme on peut l'apercevoir dans les requêtes kerberos ci-dessous, nous sommes dans un domaine nommé **C137.LOCAL**.

Les deux machines sont : 
- DESKTOP-SDN1RPT$ soit  10.42.85.115
- CITADEL-DC01 soit 10.42.85.10

On peut identifier plusieurs utilisateurs :
- mortysmith/C137
- ricksanchez/C137
- Administrator/C137.LOCAL


# 3. Reconnaissance périmétrique

Maintenant que nous avons pu faire un peu de reco sur nos données et identifier qui était quoi dans notre jeu de donnée, nous allons explorer notre première hypothèse. 

**Hypothèse 1** : un RAT : Remote Access Trojan a été implanté sur le parc. On pourrait avoir un malware implanté sur une de nos deux machines qui communiquerait avec une IP externe pour recevoir ses ordres. En effet, étant donné que nous avons été dépêché pour analyser cet incident, une menace de ce type est probable.

Commençons par regarder nos logs DNS :

In [10]:
dns = datasets['dns']
agg = (dns.groupby(["query", "rejected"]).size()
      .reset_index(name="count")
      .sort_values("count", ascending=False)
)
agg

,query,rejected,count
357,wpad,False,192
15,WPAD,False,72
195,isatap,False,52
287,settings-win.data.microsoft.com,False,45
14,ISATAP,False,39
...,...,...,...
17,_ldap._tcp.default-first-site-name._sites.c137.local,False,1
23,a-0003.a-msedge.net,False,1
21,_ldap._tcp.default-first-site-name._sites.forestdnszones.c137.local,False,1
354,wildcard.weather.microsoft.com.edgekey.net,False,1


On va filtrer pour ne garder que ce qui nous intéresse : 

In [11]:
agg[(agg["count"] > 1) & (agg["count"] < 30)][:20]

,query,rejected,count
11,C137,False,29
77,c137,False,24
202,login.live.com,False,21
355,win8.ipv6.microsoft.com,False,21
58,assets.msn.com,False,18
95,checkappexec.microsoft.com,False,17
13,DESKTOP-SDN1RPT,False,16
190,img-s-msn-com.akamaized.net,False,16
75,c.msn.com,False,15
51,arc.msn.com,False,15


On va maintenant regarder du côté des IP externes les plus contactées par des ip internes :

In [12]:
filtered = conn[
    conn["id.orig_h"].isin(internal_ips) &
    ~conn["id.resp_h"].isin(internal_ips)
]

agg = (
  filtered.groupby(["id.orig_h", "id.resp_h", "id.resp_p"])
      .size()
      .reset_index(name="count")
      .sort_values("count", ascending=False)
)
agg[:10]

,id.orig_h,id.resp_h,id.resp_p,count
2,10.42.85.10,192.168.45.1,53,584
18,10.42.85.115,10.90.90.90,443,354
152,10.42.85.115,208.80.153.240,443,72
8,10.42.85.10,224.0.0.252,5355,67
146,10.42.85.115,204.79.197.203,443,47
258,10.42.85.115,72.21.91.29,80,46
151,10.42.85.115,208.80.153.224,443,45
213,10.42.85.115,40.91.125.0,443,40
144,10.42.85.115,204.79.197.200,443,39
254,10.42.85.115,70.37.74.6,443,38


Dans les IP externes les plus contactées on a donc :
- 192.168.45.1 ( probablement le resolveur DNS local car contacté sur le port 53)
- 10.90.90.90
- 208.80.153.240
Si on regarde par quel nom de domaine ces IP sont résolues :
- 10.90.90.90 : settings-win.data.microsoft.com
- 208.80.153.240 : upload.wikimedia.org

Ces connexions ne sont à priori pas très suspectes, on va essayer de tenter une autre hypothèse : et si une IP externe avait abusé d'un des services de notre entreprise pour rentrer ? **L'hypothèse 1 semble à priori invérifiée**. 

**Hypothèse 2** : la connexion malveillante vient plutôt de l'extérieur vers notre parc. alors il faut chercher les connexions d'IP externes vers nos IP privées : 

In [13]:
filtered = conn[
    ~conn["id.orig_h"].isin(internal_ips) &
    conn["id.resp_h"].isin(internal_ips)
]

agg = (
  filtered.groupby(["id.orig_h", "id.resp_h", "id.resp_p"])
      .size()
      .reset_index(name="count")
      .sort_values("count", ascending=False)
)
agg[:10]

,id.orig_h,id.resp_h,id.resp_p,count
4,194.61.24.102,10.42.85.10,3389,29309
0,194.61.24.102,10.42.85.10,0,1
1,194.61.24.102,10.42.85.10,14,1
2,194.61.24.102,10.42.85.10,80,1
3,194.61.24.102,10.42.85.10,443,1


Alors cette fois on a quelque chose d'intéressant :

On a l'IP externe **194.61.24.102** qui se connecte sur une IP interne **10.42.85.10** qui est donc le contrôleur de domaine, sur le port 3389 (RDP). Cela est très étonnant. Si on regarde ça de plus près dans les logs rdp :

In [14]:
rdp = datasets['rdp']
rdp["dt_utc"] = pd.to_datetime(rdp["ts"], unit="s", utc=True)
filtered = rdp[rdp['id.resp_h'] == '10.42.85.10']
filtered[['dt_utc', 'id.orig_h', 'id.resp_h', 'id.resp_p', 'cookie']][:10]

,dt_utc,id.orig_h,id.resp_h,id.resp_p,cookie
0,2020-09-19 02:19:26.549144983+00:00,194.61.24.102,10.42.85.10,3389,nmap
1,2020-09-19 02:21:26.112469912+00:00,194.61.24.102,10.42.85.10,3389,Administrator
2,2020-09-19 02:21:26.342463017+00:00,194.61.24.102,10.42.85.10,3389,Administrator
3,2020-09-19 02:21:26.564666033+00:00,194.61.24.102,10.42.85.10,3389,Administrator
4,2020-09-19 02:21:26.786791086+00:00,194.61.24.102,10.42.85.10,3389,Administrator
5,2020-09-19 02:21:27.001408100+00:00,194.61.24.102,10.42.85.10,3389,Administrator
6,2020-09-19 02:21:27.224504948+00:00,194.61.24.102,10.42.85.10,3389,Administrator
7,2020-09-19 02:21:27.437500954+00:00,194.61.24.102,10.42.85.10,3389,Administrator
8,2020-09-19 02:21:27.661672115+00:00,194.61.24.102,10.42.85.10,3389,Administrator
9,2020-09-19 02:21:27.887578964+00:00,194.61.24.102,10.42.85.10,3389,Administrator


Ci-dessus on peut remarquer que la première connexion RDP **194.61.24.102** -> **10.42.85.10** a eu lieu le **2020-09-19 à 02:19:26**.

Le champ cookie nous indique que l'outil **nmap** a probablement été utilisé pour faire du repérage sur la machine. 
Deux minutes plus tard, on a des tentatives de connexions qui commencent à être visibles avec le compte administrateur toujours depuis la même IP.
Ces connexions ressemblent forcement à un bruteforce étant donné le rapprochement entre chaque connexion. 

On peut même utiliser la visualition pour observer ces différentes connexions RDP dans notre dataset : 

In [15]:
from msticpy.vis import mp_pandas_plot

filtered.mp_plot.timeline(time_column="dt_utc");

Loading BokehJS ...

A priori zeek ne nous donne pas tellement plus de détails sur la connexion. On peut déjà considérer que du bruteforce a eu lieu. 
Etant donné la visualisation ci-dessus, on peut imaginer que le bruteforce à eu lieu à 22h UTC le 18-09-2020 car les points y sont très ressérés.

Puis l'attaquant a exploité son accès à partir de 00h38 UTC jusqu'à 05h38 UTC le 19-09-2020. **L'hypothèse 2 est vérifiée.**

**Hypothèse 3** : l'hôte a bien été compromis et a été utilisé par la suite dans d'autres connexions réseau par l'attaquant.

A nous de vérifier cela. On va regarder toutes les requêtes réalisées par 10.42.85.10 à partir de minuit. 

In [16]:
moment = pd.Timestamp("2020-09-19 00:00:00", tz="UTC")
filtered = conn[
    (conn["id.orig_h"] == "10.42.85.10") & 
    (conn["dt_utc"] >= moment)
]
agg = (
  filtered.groupby(["id.orig_h", "id.resp_h", "id.resp_p"])
      .size()
      .reset_index(name="count")
      .sort_values("count", ascending=False)
)
agg

,id.orig_h,id.resp_h,id.resp_p,count
3,10.42.85.10,192.168.45.1,53,219
8,10.42.85.10,224.0.0.252,5355,51
2,10.42.85.10,10.42.85.255,138,26
1,10.42.85.10,10.42.85.255,137,26
4,10.42.85.10,194.61.24.102,80,4
5,10.42.85.10,203.78.103.109,443,3
15,10.42.85.10,72.21.91.29,80,3
0,10.42.85.10,10.42.85.115,3389,2
7,10.42.85.10,204.79.197.200,443,2
6,10.42.85.10,204.79.197.200,80,2


Ci-dessus on peut commencer par remarquer une connexion de la part de notre hôte compromis sur le port 80 de la machine attaquante. On le voit dans la connexion :

10.42.85.10 ->	194.61.24.102:80

Et port 80 = HTTP. On peut utiliser notre log zeek qui lit le http afin d'analyser cette connexion.

In [17]:
http = datasets["http"]

filtered = http[
    (http['id.orig_h'] == '10.42.85.10') &
    (http['id.resp_h'] == '194.61.24.102')
]
filtered

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,trans_depth,method,host,uri,version,user_agent,request_body_len,response_body_len,status_code,status_msg,tags,resp_fuids,resp_mime_types,ja4h,referrer,resp_filenames,orig_fuids,orig_mime_types,dt_utc
119,1.600482e+09,CnoaM645MJwgK59pe2,10.42.85.10,62408,194.61.24.102,80,1,GET,194.61.24.102,/,1.0,Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko,0,228,200,OK,[],[FSW2SG3GRopRAgapPh],[text/html],ge11nn06enus_8c2f9ef95269_000000000000_000000000000,NaN,NaN,NaN,NaN,2020-09-19 02:23:41.731918097+00:00
120,1.600482e+09,CumDlK3AslCr8accbd,10.42.85.10,62407,194.61.24.102,80,1,GET,194.61.24.102,/favicon.ico,1.0,Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko,0,195,404,File not found,[],[FSH3I94gUnCIBJ8V7g],[text/html],ge11nn050000_a72e37bb2523_000000000000_000000000000,NaN,NaN,NaN,NaN,2020-09-19 02:23:41.797122955+00:00
121,1.600482e+09,CX4ANEpyjWQJPLv17,10.42.85.10,62410,194.61.24.102,80,1,GET,194.61.24.102,/coreupdater.exe,1.0,Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko,0,7168,200,OK,[],[F15zmh1fD5AVKS9HX9],[application/x-dosexec],ge11nr050000_a72e37bb2523_000000000000_000000000000,http://194.61.24.102/,NaN,NaN,NaN,2020-09-19 02:24:06.939239025+00:00


Ci-dessus on peut voir qu'après avoir accédé à **http://194.61.24[.]102/** l\'utiliseur télécharge le fichier 

**http://194.61.24[.]102/coreupdater.exe** avec un navigateur qui pourrait être mozilla firefox étant donné le user agent ( indique le logiciel utilisé mais peut être modifié très facilement) à 02:24:06 le 2020-09-19.

**L'hypothèse 3 est bien vérifiée, étant donné que les actions qu'on a pu identifier semblent bien malveillantes.**

**Hypothèse 4**: s'il s'agit d'un attaquant, le logiciel **coreupdater.exe** est probablement un outil malveillant ou même un RAT ( Remote Access Tool ) qui lui permettra de se laisser un accès dans le réseau.

Utilisons maintenant le dataset zeek qui permet de lister les fichiers, en pivotant sur l'UID. L'UID est un identifiant unique qui permet de retrouver la même session entre tous les fichiers de log zeek.



In [18]:
files = datasets["files"]
files[files["uid"] == "Cvs2R1E6eZqAKtKT"]

,ts,fuid,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,source,depth,analyzers,mime_type,duration,local_orig,is_orig,seen_bytes,missing_bytes,overflow_bytes,timedout,extracted,extracted_cutoff,total_bytes,filename,dt_utc


Ok maintenant on peut regarder le binaire situé dans **extract_files/extract-1600482246.939862-HTTP-F15zmh1fD5AVKS9HX9**.

Si on utilise le plus grand outil de reverse de tous les temps :

```
[nobisd@investmachine network_investigation]$ file extract_files/extract-1600482246.939862-HTTP-F15zmh1fD5AVKS9HX9
extract_files/extract-1600482246.939862-HTTP-F15zmh1fD5AVKS9HX9: PE32+ executable for MS Windows 4.00 (GUI), x86-64, 3 sections
[nobisd@investmachine network_investigation]$ strings extract_files/extract-1600482246.939862-HTTP-F15zmh1fD5AVKS9HX9
!This program cannot be run in DOS mode.
Rich}E
.text
`.rdata
@.lhru
PAYLOAD:
ExitProcess
VirtualAlloc
KERNEL32.dll
H1X'H-
z"7T
qUo'
+7CS
q]k*7E_Z
C.9w
uc7.
w/Fu
`_;w
]wcw
../J."
+7VV
C!_.
KERNEL32.dll
VirtualAlloc
ExitProcess
```

On remarque que le programme mentionne une fonction nommée VirtualAlloc, qui peut tout à faire servir à allouer de la mémoire pour exécuter du code malveillant. Ici nous n'irons pas plus loin sur l'analyse du binaire car nous allons considérer avec les éléments à notre disponition que le celui-ci est malveillant. On va considérer que **l'hypothèse 4 est vérifiée.**

**Hypothèse 5** : après avoir été installé sur le poste, le malware nommé **coreupdater.exe** a communiqué avec un serveur pour recevoir ses ordres. Il s'agit maintenant de trouver ce canal de communication. On va maintenant regarder les communications effectuées par le poste compromis après à 02:24:06 le 2020-09-19, l'heure de téléchargement du malware.

In [19]:
moment = pd.Timestamp("2020-09-19 02:24:00", tz="UTC")
filtered = conn[
    (conn["id.orig_h"] == "10.42.85.10") & 
    (conn["dt_utc"] >= moment)
]
agg = (
  filtered.groupby(["id.orig_h", "id.resp_h", "id.resp_p"])
      .size()
      .reset_index(name="count")
      .sort_values("count", ascending=False)
)
agg

,id.orig_h,id.resp_h,id.resp_p,count
3,10.42.85.10,192.168.45.1,53,179
6,10.42.85.10,224.0.0.252,5355,41
1,10.42.85.10,10.42.85.255,137,22
2,10.42.85.10,10.42.85.255,138,17
5,10.42.85.10,203.78.103.109,443,3
0,10.42.85.10,10.42.85.115,3389,2
4,10.42.85.10,194.61.24.102,80,2
11,10.42.85.10,72.21.91.29,80,2
10,10.42.85.10,23.60.139.27,80,2
7,10.42.85.10,23.32.45.37,80,1


**Hypothèse 5 invérifiée**, après analyse approfondie pas de traces supplémentaire de l'utilisation d'un C2. Maintenant peut-être que le binaire malveillant a été installé comme persistence. **Cette hypothèse est invérifiable avec les logs réseau seuls**.

**Hypothèse 6** : l'attaquant après avoir mis un pied sur la machine a exploité son accès pour continuer son infection dans le réseau. Ci-dessus, on peut voir une connexion sur le port 3389 sur la machine 10.42.85.115. Peut-être que notre attaquant s'est déplacé via rdp sur une nouvelle machine.

In [20]:
rdp[
    (rdp["id.orig_h"] == "10.42.85.10") & 
    (rdp["id.resp_h"] == "10.42.85.115")
]

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,cookie,result,security_protocol,cert_count,dt_utc
99,1.600483e+09,C6Usta2iBwZjlfCNv1,10.42.85.10,62514,10.42.85.115,3389,,encrypted,HYBRID_EX,0,2020-09-19 02:35:55.291953087+00:00


A priori c'est bien le cas, et en plus à **2020-09-19 02:35:55.291953087+00:00**. Ce qui semble confirmer notre théorie étant donné la corrélation temporelle entre la compromission du premier serveur et celui-ci. **L'hypothèse 6 est donc vérifiée.**

**Hypothèse 7**: après s'être déplacé de la machine **10.42.85.10** à la machine **10.42.85.115**, l'attaquant a ensuite utilisé ses accès pour réaliser de nouvelles connexions malveillantes. Vérifions cela en analysant les connexions depuis 10.42.85.115 à partir de 2h35. 

In [21]:
moment_start = pd.Timestamp("2020-09-19 02:35:00", tz="UTC")
moment_end = pd.Timestamp("2020-09-19 04:35:00", tz="UTC")

filtered = conn[
    (conn["id.orig_h"] == "10.42.85.115") & 
    (conn["dt_utc"] >= moment_start) &
    (conn["dt_utc"] <= moment_end)

]
agg = (
  filtered.groupby(["id.orig_h", "id.resp_p"])
      .size()
      .reset_index(name="count")
      .sort_values("count", ascending=False)
)
agg

,id.orig_h,id.resp_p,count
6,10.42.85.115,443,270
0,10.42.85.115,53,144
1,10.42.85.115,80,49
5,10.42.85.115,389,40
2,10.42.85.115,88,17
4,10.42.85.115,135,16
9,10.42.85.115,49155,16
7,10.42.85.115,445,12
3,10.42.85.115,123,7
10,10.42.85.115,49158,2


Regardons de plus près les connexions kerberos. ça pourra nous donner une idée des volontés de l'attaquant.

In [22]:
moment = pd.Timestamp("2020-09-19 02:35:00", tz="UTC")
filtered = kerberos[
    (kerberos["id.orig_h"] == "10.42.85.115") & 
    (kerberos["dt_utc"] >= moment)
]
filtered[:20]

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,request_type,client,service,success,error_msg,till,forwardable,renewable,cipher,dt_utc
42,1.600483e+09,CANED3EgI1XPt54B,10.42.85.115,50694,10.42.85.10,88,AS,Administrator/C137.LOCAL,krbtgt/C137.LOCAL,0.0,KDC_ERR_PREAUTH_REQUIRED,2.136423e+09,1.0,1.0,NaN,2020-09-19 02:36:24.902311087+00:00
43,1.600483e+09,CPqjYx27pbad9k6R91,10.42.85.115,50695,10.42.85.10,88,AS,Administrator/C137.LOCAL,krbtgt/C137.LOCAL,1.0,NaN,2.136423e+09,1.0,1.0,aes256-cts-hmac-sha1-96,2020-09-19 02:36:24.913220882+00:00
44,1.600483e+09,Cw1Pov1NdEUKQTXZX,10.42.85.115,50696,10.42.85.10,88,TGS,Administrator/C137.LOCAL,host/desktop-sdn1rpt.c137.local,1.0,NaN,2.136423e+09,1.0,1.0,aes256-cts-hmac-sha1-96,2020-09-19 02:36:24.914736032+00:00
45,1.600483e+09,Cw6gmJ1erTRm7SSyZi,10.42.85.115,50699,10.42.85.10,88,TGS,Administrator/C137.LOCAL,LDAP/CITADEL-DC01.C137.local/C137.local,1.0,NaN,2.136423e+09,1.0,1.0,aes256-cts-hmac-sha1-96,2020-09-19 02:36:24.971004009+00:00
46,1.600483e+09,CVr2mE4rRE7Yk2nhQ8,10.42.85.115,50702,10.42.85.10,88,TGS,Administrator/C137.LOCAL,cifs/CITADEL-DC01,1.0,NaN,2.136423e+09,1.0,1.0,aes256-cts-hmac-sha1-96,2020-09-19 02:36:24.986465931+00:00
47,1.600483e+09,CmaB9T1MuUKtJZ6Wpk,10.42.85.115,50703,10.42.85.10,88,TGS,Administrator/C137.LOCAL,krbtgt/C137.LOCAL,1.0,NaN,2.136423e+09,1.0,1.0,aes256-cts-hmac-sha1-96,2020-09-19 02:36:24.987912893+00:00
48,1.600483e+09,C53ZuZ2mqaVgY1adF3,10.42.85.115,50711,10.42.85.10,88,TGS,Administrator/C137.LOCAL,cifs/CITADEL-DC01.C137.local,1.0,NaN,2.136423e+09,1.0,1.0,aes256-cts-hmac-sha1-96,2020-09-19 02:36:26.761493921+00:00
49,1.600483e+09,CIbvQG2XxNYgn9Xvuk,10.42.85.115,50712,10.42.85.10,88,TGS,Administrator/C137.LOCAL,ProtectedStorage/CITADEL-DC01.C137.local,1.0,NaN,2.136423e+09,1.0,1.0,aes256-cts-hmac-sha1-96,2020-09-19 02:36:26.767080069+00:00
50,1.600483e+09,Cv9zus4cHobNRdC0Vj,10.42.85.115,50701,10.42.85.10,445,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-09-19 02:36:24.989061117+00:00
51,1.600483e+09,CUUYBx4UHAzT8cQUN6,10.42.85.115,50710,10.42.85.10,445,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-09-19 02:36:26.764122009+00:00


On voit qu'un utilisateur ( probablement l'attaquant ) arrive à se connecter avec **Administrator/C137.LOCAL** sur les services :
- host/desktop-sdn1rpt.c137.local
- LDAP/CITADEL-DC01.C137.local/C137.local
- cifs/CITADEL-DC01.C137.local
- ProtectedStorage/CITADEL-DC01.C137.local

Et tout cela à 2h36. Regardons de plus près les connexions SMB qui ont suivi :

In [23]:
smb = datasets['smb_mapping']
moment = pd.Timestamp("2020-09-19 02:35:00", tz="UTC")
filtered = smb[
    (smb["id.orig_h"] == "10.42.85.115") & 
    (smb["dt_utc"] >= moment)
]
filtered[:20]

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,path,share_type,dt_utc
7,1.600483e+09,Cv9zus4cHobNRdC0Vj,10.42.85.115,50701,10.42.85.10,445,\\CITADEL-DC01\IPC$,PIPE,2020-09-19 02:36:24.989968061+00:00
8,1.600483e+09,Cv9zus4cHobNRdC0Vj,10.42.85.115,50701,10.42.85.10,445,\\CITADEL-DC01\NETLOGON,DISK,2020-09-19 02:36:24.991329908+00:00
9,1.600483e+09,CUUYBx4UHAzT8cQUN6,10.42.85.115,50710,10.42.85.10,445,\\CITADEL-DC01.C137.local\IPC$,PIPE,2020-09-19 02:36:26.765434027+00:00
10,1.600483e+09,Ct1lLe3FEF90ZjZYHh,10.42.85.115,50881,10.42.85.10,445,\\CITADEL-DC01.C137.local\IPC$,PIPE,2020-09-19 02:43:21.558957100+00:00
11,1.600484e+09,C6AQV5zvvVWvgubia,10.42.85.115,50917,10.42.85.10,445,\\CITADEL-DC01.C137.local\IPC$,PIPE,2020-09-19 02:58:21.583658934+00:00
12,1.600485e+09,CXGM4m4icz15ZEMgrh,10.42.85.115,50921,10.42.85.10,445,\\CITADEL-DC01.C137.local\IPC$,PIPE,2020-09-19 03:13:21.587025881+00:00
13,1.600486e+09,CdVayh1SG5dXCaEwTg,10.42.85.115,50926,10.42.85.10,445,\\CITADEL-DC01.C137.local\IPC$,PIPE,2020-09-19 03:28:21.601809978+00:00
14,1.600486e+09,Cwn3Ig1qdlAw1NC24e,10.42.85.115,50935,10.42.85.10,445,\\CITADEL-DC01.C137.local\sysvol,DISK,2020-09-19 03:30:14.835269928+00:00
15,1.600487e+09,CO1o8Q2aVTNym7QwTe,10.42.85.115,50936,10.42.85.10,445,\\CITADEL-DC01.C137.local\IPC$,PIPE,2020-09-19 03:43:21.622380972+00:00
16,1.600488e+09,C1wlV9rfjyW7SuxYa,10.42.85.115,50944,10.42.85.10,445,\\CITADEL-DC01.C137.local\IPC$,PIPE,2020-09-19 03:58:21.654272079+00:00


Regardons également les connexions dce_rcp :

In [24]:
rpc = datasets['dce_rpc']
moment = pd.Timestamp("2020-09-19 02:35:00", tz="UTC")
filtered = rpc[
    (rpc["dt_utc"] >= moment)
]
filtered[:20]

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,rtt,named_pipe,endpoint,operation,dt_utc
109,1.600483e+09,CpY88o2KgTinppVQU4,10.42.85.115,50697,10.42.85.10,135,0.000227,135,epmapper,ept_map,2020-09-19 02:36:24.947478056+00:00
110,1.600483e+09,CJUhih1JEWJsYjZMcc,10.42.85.115,50698,10.42.85.10,49155,0.000286,49155,lsarpc,LsarLookupNames4,2020-09-19 02:36:24.949039936+00:00
111,1.600483e+09,CJUhih1JEWJsYjZMcc,10.42.85.115,50698,10.42.85.10,49155,0.000216,49155,lsarpc,LsarLookupNames4,2020-09-19 02:36:24.949929953+00:00
112,1.600483e+09,CpY88o2KgTinppVQU4,10.42.85.115,50697,10.42.85.10,135,0.000155,135,epmapper,ept_map,2020-09-19 02:36:24.970107079+00:00
113,1.600483e+09,CJUhih1JEWJsYjZMcc,10.42.85.115,50698,10.42.85.10,49155,0.000161,49155,drsuapi,DRSBind,2020-09-19 02:36:24.973886013+00:00
114,1.600483e+09,CJUhih1JEWJsYjZMcc,10.42.85.115,50698,10.42.85.10,49155,0.000266,49155,drsuapi,DRSCrackNames,2020-09-19 02:36:24.974391937+00:00
115,1.600483e+09,CJUhih1JEWJsYjZMcc,10.42.85.115,50698,10.42.85.10,49155,0.000256,49155,drsuapi,DRSCrackNames,2020-09-19 02:36:24.974839926+00:00
116,1.600483e+09,CJUhih1JEWJsYjZMcc,10.42.85.115,50698,10.42.85.10,49155,0.000160,49155,drsuapi,DRSUnbind,2020-09-19 02:36:24.975193977+00:00
117,1.600483e+09,CpY88o2KgTinppVQU4,10.42.85.115,50697,10.42.85.10,135,0.000251,135,epmapper,ept_map,2020-09-19 02:36:24.978976011+00:00
118,1.600483e+09,CMYpOwV7U84h5Ow8c,10.42.85.115,50700,10.42.85.10,49158,0.000412,49158,netlogon,NetrLogonGetDomainInfo,2020-09-19 02:36:24.980287075+00:00


Ci-dessus, il semble que l'attaquant essaye d'obtenir des informations variées sur le domaine notamment l'utilisation de procédures telles que :
- LsarLookupSids*
- NtrLogonGetDomainInfo

Cependant, l'utilisation de `bkrp_BackupKey` est assez inquiétant. En effet, d'après la documentation microsoft cette procédure permet de récupérer des clefs stockées sur l'active directory en se connectant avec l'utilisateur qui en a le droit. A priori étant donné que l'attaquant a trouvé le mot de passe de Administrator, on peut considérer qu'il en a le droit. Après la lecture de la page https://www.dsinternals.com/en/dpapi-backup-key-theft-auditing/. Il semble que l'API en question peut servir spécifiquement à extraire la clef de backup de DPAPI qui permet de stocker les secrets locaux. Ainsi, on peut imaginer que l'attaquant a volé les secrets de connexions présents sur la machine 10.42.85.115 qui est la machine ne travail. Pour ajouter un peu de détail, on a pu voir plus haut une requête kerberos ProtectedStorage/CITADEL-DC01.C137.local à la même seconde que l'utilation de la procédure `bkrp_BackupKey`. Il s'agit de la requête d'authentification parsée par zeek. 

**L'hypothèse 7 est donc vérifiée**. L'attaquant a utilisé ses accès pour extraire des secrets de connexion sur le parc à **2020-09-19 02:36:26**.

Il est problable que les secrets volés ont été utilisés par l'attaquant pour voler la recette secrète. On a déjà une bonne idée de cela dans les recherches précédentes. Cependant, en relisant les requêtes précédentes on ne trouve rien qui nous alarme vraiment sur l'utilisation de la machine **10.42.85.115** après les méfaits déjà identifiés. Mais peut-être que l'attaquant a déjà utilisé les secrets sur le contrôleur de domaine car c'est celui-ci qui stockait la recette d'après la description du scénario. Dans ce cas, aucune autre requête ne pourrait nous montrer l'extraction de la sauce de Szechuan. Il faudrait compléter l'article actuel avec une analyse du contrôleur de domaine et de la machine cliente.

TODO :
- Est-ce qu'on a un DCSync ?
- Nuancer sur le vol de secrets

In [25]:
!pip install pandoc


[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
