[
    uuid(cd99b06b-0c7b-422a-80da-1cb5758adbec),
    version(1.0)
]
interface MyInterface
{
    // Launch a command asynchronously and return a command ID
    int LaunchCommand(
        [in] handle_t hBinding,
        [in, string] char* command
    );
    
    // Get the output of a running/completed command
    int GetCommandOutput(
        [in] handle_t hBinding,
        [in] int command_id,
        [out, string] char** output,
        [out] int* is_finished
    );
    
    // Stop/kill a running command
    int StopCommand(
        [in] handle_t hBinding,
        [in] int command_id
    );
}
